// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package enum

import (
	"fmt"
)

type SortOrder string

const (
	// SortOrderDesc: descending order
	SortOrderDesc SortOrder = "desc"
	// SortOrderAsc: ascending order
	SortOrderAsc SortOrder = "asc"
)

var SortOrderINVALID SortOrder // zero value
var ErrNoSortOrder = fmt.Errorf("no SortOrder")

func (v SortOrder) Validate() error {
	switch v {
	case SortOrderDesc, SortOrderAsc:
		return nil
	case SortOrderINVALID:
		return fmt.Errorf("invalid zero value %v: %w", ErrNoSortOrder)
	default:
		return fmt.Errorf("unexpected value %v: %w", ErrNoSortOrder)
	}
}

func MustSortOrder(v string) SortOrder {
	retval := SortOrder(v)
	if err := retval.Validate(); err != nil {
		panic(err)
	}
	return retval
}

func ListSortOrder() []SortOrder {
	return []SortOrder{SortOrderDesc, SortOrderAsc}
}
