// +build apikit

// this code is generated by "apikit init"

package main

import (
	"context"
	"log"
	"m/12with-auth/action"
	"m/12with-auth/auth"
	"m/12with-auth/design"

	"github.com/podhmo/apikit/pkg/emitgo"
	"github.com/podhmo/apikit/web"
	genchi "github.com/podhmo/apikit/web/webgen/gen-chi"
)

// generate code: VERBOSE=1 go run gen.go

func main() {
	if err := run(); err != nil {
		log.Fatalf("!! %+v", err)
	}
}

func run() (err error) {
	emitter := emitgo.NewConfigFromRelativePath(action.Hello, "..").NewEmitter()
	emitter.FilenamePrefix = "gen_" // generated file name is "gen_<name>.go"
	defer emitter.EmitWith(&err)

	r := web.NewRouter()
	// todo: conflict-check
	r.Get("/hello", action.Hello)
	r.Get("/hello-with-auth", action.Hello, web.WithExtraDependencies(auth.LoginRequired), web.WithRename("HelloWithAuth"))
	r.Get("/hello-with-auth-with-db", action.Hello, web.WithExtraDependencies(auth.LoginRequiredWithDB), web.WithRename("HelloWithAuthWithDB"))

	c := genchi.DefaultConfig()
	// c.Override("logger", action.NewLogger)

	g := c.New(emitter)
	return g.Generate(
		context.Background(),
		r,
		design.HTTPStatusOf,
	)
}
