// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package runner

import (
	"m/00same-package/design"
)

type Component interface {
	DB() *design.DB
	Messenger() (*design.Messenger, error)
}
