// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.


package runner

import (
	"m/00same-package/design"
)

func SendMessage(component Component, title string) error {
	var m *design.Messenger
	{
		var err error
		m, err = component.Messenger()
		if err != nil {
			return err
		}
	}
	return design.SendMessage(m, title)
}
