package code

import (
	"fmt"
	"io"

	"github.com/podhmo/apikit/pkg/tinypkg"
	"github.com/podhmo/apikit/resolve"
)

const (
	PriorityFirst   = -10
	PrioritySecond  = -1
	PriorityDefault = 0
)

type EmitCodeFunc func(w io.Writer, code *Code) error

type Config struct {
	Header        string
	DisableFormat bool

	EmitCodeFunc EmitCodeFunc
	Resolver     *resolve.Resolver
}

func DefaultConfig() *Config {
	c := &Config{
		Header:        Header,
		DisableFormat: false,
		Resolver:      resolve.NewResolver(),
	}
	c.EmitCodeFunc = c.defaultEmitCodeFunc
	return c
}

const Header = `// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

`

func (c *Config) defaultEmitCodeFunc(w io.Writer, code *Code) error {
	fmt.Fprintln(w, c.Header)
	fmt.Fprintf(w, "package %s\n\n", code.Here.Name)

	collector := tinypkg.NewImportCollector(code.Here)
	if err := code.CollectImports(collector); err != nil {
		return err
	}
	imports := collector.Imports
	if err := code.EmitImports(w, imports); err != nil {
		if err != ErrNoImports {
			return err
		}
	} else {
		io.WriteString(w, "\n")
	}
	return code.EmitCode(w)
}

func (c *Config) NewCode(
	here *tinypkg.Package,
	name string,
	emitCode func(w io.Writer) error,
) *Code {
	return &Code{
		Name:     name,
		Here:     here,
		EmitCode: emitCode,
		Config:   c,
	}
}
