// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package handler

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

func Mount(r chi.Router, getProvider func(*http.Request) (*http.Request, Provider, error)) {
	r.Get("/hello", Hello(getProvider))
}
