// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package handler

import (
	"m/14openapi-petstore/action"
	"m/14openapi-petstore/handler/runtime"
	"net/http"
)

func FindPets(getProvider func(*http.Request) (*http.Request, Provider, error)) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, req *http.Request) {
		req, provider, err := getProvider(req)
		if err != nil {
			runtime.HandleResult(w, req, nil, err)
			return
		}
		var p *action.PetStore
		{
			p = provider.PetStore()
		}
		var queryParams struct {
			tag   *string `query:"tag"`
			limit *int32  `query:"limit"`
		}
		if err := runtime.BindQuery(&queryParams, req); err != nil {
			_ = err // ignored
		}
		result, err := action.FindPets(p, queryParams.tag, queryParams.limit)
		runtime.HandleResult(w, req, result, err)
	}
}
