// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package handler

import (
	"m/14openapi-petstore/action"
	"main/handler/runtime"
	"net/http"
)

func FindPetByID(getProvider func(*http.Request) (*http.Request, Provider, error)) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, req *http.Request) {
		var pathParams struct {
			id int64 `path:"id,required"`
		}
		if err := runtime.BindPathParams(&pathParams, req, "id"); err != nil {
			w.WriteHeader(404)
			runtime.HandleResult(w, req, nil, err)
			return
		}
		req, provider, err := getProvider(req)
		if err != nil {
			runtime.HandleResult(w, req, nil, err)
			return
		}
		var p *action.PetStore
		{
			p = provider.PetStore()
		}
		result, err := action.FindPetByID(p, pathParams.id)
		runtime.HandleResult(w, req, result, err)
	}
}
