// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package handler

import (
	"github.com/go-chi/chi/v5"
	"net/http"
)

func Mount(r chi.Router, getProvider func(*http.Request) (*http.Request, Provider, error)) {
	r.Post("/pets", AddPet(getProvider))
	r.Get("/pets", FindPets(getProvider))
	r.Get("/pets/{id}", FindPetByID(getProvider))
	r.Delete("/pets/{id}", DeletePet(getProvider))
}
