// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package handler

import (
	"context"
	"m/11web/design"
	"m/11web/handler/runtime"
	"net/http"
)

func PostArticleComment(getProvider func(*http.Request) (*http.Request, Provider, error)) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, req *http.Request) {
		var pathParams struct {
			articleID int64 `path:"articleId,required"`
		}
		if err := runtime.BindPathParams(&pathParams, req, "articleId"); err != nil {
			w.WriteHeader(404)
			runtime.HandleResult(w, req, nil, err)
			return
		}
		req, provider, err := getProvider(req)
		if err != nil {
			runtime.HandleResult(w, req, nil, err)
			return
		}
		var ctx context.Context = req.Context()
		var db *design.DB
		{
			var err error
			db, err = provider.DB(ctx)
			if err != nil {
				runtime.HandleResult(w, req, nil, err)
				return
			}
		}
		var data design.Comment
		if err := runtime.BindBody(&data, req.Body); err != nil {
			w.WriteHeader(400)
			runtime.HandleResult(w, req, nil, err)
			return
		}
		if err := runtime.ValidateStruct(&data); err != nil {
			w.WriteHeader(422)
			runtime.HandleResult(w, req, nil, err)
			return
		}
		result, err := design.PostArticleComment(ctx, db, pathParams.articleID, data)
		runtime.HandleResult(w, req, result, err)
	}
}
