// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package handler

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

func Mount(r chi.Router, getProvider func(*http.Request) (*http.Request, Provider, error)) {
	r.Post("/articles/{articleId}/comments", PostArticleComment(getProvider))
	r.Get("/articles", ListArticle(getProvider))
	r.Get("/articles/{articleId}", GetArticle(getProvider))
}
