// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.

package handler

import (
	"context"
	"github.com/podhmo/apikit/web/webruntime"
	"m/11web/design"
	"net/http"
)

func GetArticle(getProvider func(*http.Request) (*http.Request, Provider, error)) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, req *http.Request) {
		articleID := webruntime.PathParam(req, "articleId")
		req, provider, err := getProvider(req)
		if err != nil {
			webruntime.HandleResult(w, req, nil, err)
			return
		}
		ctx := req.Context()
		var db *design.DB
		{
			var err error
			db, err = provider.DB(ctx)
			if err != nil {
				webruntime.HandleResult(w, req, nil, err)
				return
			}
		}
		result, err := design.GetArticle(ctx, db, articleID)
		webruntime.HandleResult(w, req, result, err)
	}
}
