//go:build apikit
// +build apikit

// this code is generated by "apikit init"

package main

import (
	"context"
	"fmt"
	"log"
	"m/14openapi-petstore/action"
	"m/14openapi-petstore/design"
	"m/14openapi-petstore/myplugins/gendoc"

	"github.com/podhmo/apikit/pkg/emitgo"
	"github.com/podhmo/apikit/web"
	genchi "github.com/podhmo/apikit/web/webgen/gen-chi"
)

// generate code: VERBOSE=1 go run gen.go

func main() {
	if err := run(); err != nil {
		log.Fatalf("!! %+v", err)
	}
}

func run() (err error) {
	emitter := emitgo.NewConfigFromRelativePath(action.AddPet, "..").NewEmitter()
	emitter.FilenamePrefix = "gen_" // generated file name is "gen_<name>.go"
	defer emitter.EmitWith(&err)

	r := web.NewRouter()

	r.Get("/pets", action.FindPets)
	r.Post("/pets", action.AddPet)
	r.Get("/pets/{id}", action.FindPetByID)
	r.Delete("/pets/{id}", action.DeletePet, web.WithDefaultStatusCode(204))

	c := genchi.DefaultConfig()
	// c.Override("logger", action.NewLogger) // register provider as func() (*log.Logger, error)

	g := c.New(emitter)
	if err := g.Generate(context.Background(), r, design.HTTPStatusOf); err != nil {
		return err
	}

	// generate openapi doc via custom plugin
	type defaultError struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
	if err := g.IncludePlugin(g.RootPkg, gendoc.Options{
		OutputFile:   "docs/openapi.json",
		Handlers:     g.Handlers,
		DefaultError: defaultError{},
	}); err != nil {
		return fmt.Errorf("on gendoc plugin: %w", err)
	}
	return nil

}
