package translate

import (
	"fmt"
	"io"
	"strings"
	"testing"

	"github.com/podhmo/apikit/pkg/difftest"
	"github.com/podhmo/apikit/pkg/tinypkg"
)

func TestCode(t *testing.T) {
	pkg := tinypkg.NewPackage("foo", "")
	config := DefaultConfig()
	cases := []struct {
		msg  string
		code *Code
		want string
	}{
		{
			msg: "no-import",
			code: config.NewCode(pkg, "", func(w io.Writer) error {
				fmt.Fprintln(w, `func Hello() string { return "hello" }`)
				return nil
			}),
			want: `
// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.


package foo


func Hello() string { return "hello" }`,
		},
		{
			msg: "with-import",
			code: func() *Code {
				code := config.NewCode(pkg, "", func(w io.Writer) error {
					fmt.Fprintln(w, `func Hello(ctx context.Context) string { return "hello" }`)
					return nil
				})
				code.ImportPackages = func() ([]*tinypkg.ImportedPackage, error) {
					return []*tinypkg.ImportedPackage{
						pkg.Import(tinypkg.NewPackage("context", "")),
					}, nil
				}
				return code
			}(),
			want: `
// Code generated by "github.com/podhmo/apikit"; DO NOT EDIT.


package foo

import (
	"context"
)

func Hello(ctx context.Context) string { return "hello" }`,
		},
	}

	for _, c := range cases {
		t.Run(c.msg, func(t *testing.T) {
			var buf strings.Builder
			if err := c.code.Emit(&buf); err != nil {
				t.Fatalf("unexpected error %+v", err)
			}
			if want, got := strings.TrimSpace(c.want), strings.TrimSpace(buf.String()); want != got {
				difftest.LogDiffGotStringAndWantString(t, got, want)
			}
		})
	}
}
